import type { RouteRecordRaw } from 'vue-router'

const routes: RouteRecordRaw[] = [
  {
    path: '/',
    name: 'home',
    component: () => import('@views/HomeView.vue'),
    meta: { title: 'Thailand Travel Guide', seoKey: 'home' },
  },
  {
    path: '/visa',
    name: 'visa',
    component: () => import('@views/VisaWizardView.vue'),
    meta: { title: 'Thailand Visa Guide', seoKey: 'visa' },
  },
  {
    path: '/tdac',
    name: 'tdac',
    component: () => import('@views/TDACGuideView.vue'),
    meta: { title: 'Thailand Arrival Card Guide', seoKey: 'tdac' },
  },
  {
    path: '/onward-ticket',
    name: 'onward-ticket',
    component: () => import('@views/OnwardTicketView.vue'),
    meta: { title: 'Onward Ticket — Proof of Onward Travel', seoKey: 'onwardTicket', requiresAuth: true },
  },
  {
    path: '/warnings',
    name: 'warnings',
    component: () => import('@views/WarningsView.vue'),
    meta: { title: 'Thailand Travel Tips', seoKey: 'warnings' },
  },
  {
    path: '/attractions',
    name: 'attractions',
    component: () => import('@views/AttractionsView.vue'),
    meta: { title: 'Places to Visit in Thailand', seoKey: 'attractions' },
  },
  {
    path: '/attractions/:id',
    name: 'attraction-detail',
    component: () => import('@views/AttractionDetailView.vue'),
    meta: { title: 'Attraction', dynamicSeo: true },
  },
  {
    path: '/dashboard',
    name: 'dashboard',
    component: () => import('@views/DashboardView.vue'),
    meta: { title: 'My Dashboard', seoKey: 'dashboard', requiresAuth: true },
  },
  {
    path: '/profile',
    name: 'profile',
    component: () => import('@views/ProfileView.vue'),
    meta: { title: 'Travel Profile', seoKey: 'profile' },
  },
  {
    path: '/itinerary',
    name: 'itinerary',
    component: () => import('@views/ItineraryView.vue'),
    meta: { title: 'Trip Itinerary Planner', seoKey: 'itinerary', requiresPro: true },
  },
  {
    path: '/alerts',
    name: 'alerts',
    component: () => import('@views/AlertsView.vue'),
    meta: { title: 'Oversight Alerts', requiresPro: true },
  },
  {
    path: '/smart-match',
    name: 'smart-match',
    component: () => import('@views/SmartMatchView.vue'),
    meta: { title: 'Smart Match', requiresPro: true },
  },
  {
    path: '/packing',
    name: 'packing',
    component: () => import('@views/PackingView.vue'),
    meta: { title: 'AI Packing Assistant', requiresPro: true },
  },
  {
    path: '/safety',
    name: 'safety',
    component: () => import('@views/SafetyView.vue'),
    meta: { title: 'Thailand Safety Guide', requiresPro: true },
  },
  {
    path: '/emergency',
    name: 'emergency',
    component: () => import('@views/EmergencyView.vue'),
    meta: { title: 'Emergency Contacts — Thailand', seoKey: 'emergency' },
  },
  {
    path: '/90-day',
    name: '90-day',
    component: () => import('@views/NinetyDayView.vue'),
    meta: { title: '90-Day Reporting', requiresPro: true },
  },
  {
    path: '/medical',
    name: 'medical',
    component: () => import('@views/MedicalView.vue'),
    meta: { title: 'Medical Tourism', requiresPro: true },
  },
  {
    path: '/cost-calculator',
    name: 'cost-calculator',
    component: () => import('@views/CostCalculatorView.vue'),
    meta: { title: 'Cost of Living', requiresPro: true },
  },
  {
    path: '/setup-guide',
    name: 'setup-guide',
    component: () => import('@views/SetupGuideView.vue'),
    meta: { title: 'Thailand Setup Guide', requiresPro: true },
  },
  {
    path: '/saved',
    name: 'saved',
    component: () => import('@views/SavedPlacesView.vue'),
    meta: { title: 'Saved Places', requiresAuth: true },
  },
  {
    path: '/privacy',
    name: 'privacy',
    component: () => import('@views/PrivacyView.vue'),
    meta: { title: 'Privacy Policy' },
  },
  {
    path: '/terms',
    name: 'terms',
    component: () => import('@views/TermsView.vue'),
    meta: { title: 'Terms of Service' },
  },
  {
    path: '/contact',
    name: 'contact',
    component: () => import('@views/ContactView.vue'),
    meta: { title: 'Contact Us' },
  },
  {
    path: '/people',
    name: 'people',
    component: () => import('@views/PeopleView.vue'),
    meta: { title: 'People of Chiang Mai' },
  },
  {
    path: '/heritage',
    name: 'heritage',
    component: () => import('@views/HeritageView.vue'),
    meta: { title: 'Thailand Heritage Sites', seoKey: 'heritage' },
  },
  {
    path: '/heritage/:slug',
    name: 'heritage-detail',
    component: () => import('@views/HeritageDetailView.vue'),
    meta: { title: 'Heritage Site', dynamicSeo: true },
  },
  {
    path: '/festivals',
    name: 'festivals',
    component: () => import('@views/FestivalsView.vue'),
    meta: { title: 'Thai Festivals & Events', seoKey: 'festivals' },
  },
  {
    path: '/festivals/:slug',
    name: 'festival-detail',
    component: () => import('@views/FestivalDetailView.vue'),
    meta: { title: 'Festival', dynamicSeo: true },
  },
  {
    path: '/guides',
    name: 'guides',
    component: () => import('@views/GuidesView.vue'),
    meta: { title: 'Thailand Travel Guides', seoKey: 'guides' },
  },
  {
    path: '/guides/:slug',
    name: 'guide-detail',
    component: () => import('@views/GuideDetailView.vue'),
    meta: { title: 'Travel Guide', dynamicSeo: true },
  },
  {
    path: '/phrasebook',
    name: 'phrasebook',
    component: () => import('@views/PhrasebookView.vue'),
    meta: { title: 'Thai Phrasebook', seoKey: 'phrasebook' },
  },
  {
    path: '/visa-countdown',
    name: 'visa-countdown',
    component: () => import('@views/VisaCountdownView.vue'),
    meta: { title: 'Visa Countdown Timer', seoKey: 'visaCountdown' },
  },
  {
    path: '/about',
    name: 'about',
    component: () => import('@views/AboutView.vue'),
    meta: { title: 'About HappyRoam', seoKey: 'about' },
  },
  {
    path: '/:pathMatch(.*)*',
    name: 'not-found',
    component: () => import('@views/NotFoundView.vue'),
    meta: { title: 'Page Not Found' },
  },
]

export default routes
