import jsPDF from 'jspdf'

interface BookingPdfData {
  pnr: string
  passengerName: string
  airline: string
  origin: string
  destination: string
  departureTime: string
  arrivalTime: string
  expiresAt: string
}

export function generateBookingPdf(data: BookingPdfData): void {
  const doc = new jsPDF()

  // Title
  doc.setFontSize(24)
  doc.text('Flight Reservation Confirmation', 20, 30)

  // PNR (prominent)
  doc.setFontSize(16)
  doc.text('Booking Reference (PNR)', 20, 50)
  doc.setFontSize(28)
  doc.setFont('helvetica', 'bold')
  doc.text(data.pnr, 20, 65)

  // Passenger
  doc.setFontSize(12)
  doc.setFont('helvetica', 'normal')
  doc.text(`Passenger: ${data.passengerName}`, 20, 85)
  doc.text(`Airline: ${data.airline}`, 20, 95)

  // Route
  doc.setFontSize(14)
  doc.text(`${data.origin} \u2192 ${data.destination}`, 20, 115)
  doc.setFontSize(12)
  doc.text(`Departure: ${new Date(data.departureTime).toLocaleString()}`, 20, 130)
  doc.text(`Arrival: ${new Date(data.arrivalTime).toLocaleString()}`, 20, 140)

  // Validity
  doc.setFontSize(11)
  doc.text(`This reservation is valid until: ${new Date(data.expiresAt).toLocaleString()}`, 20, 160)

  // Disclaimer
  doc.setFontSize(9)
  doc.setTextColor(100)
  doc.text('This is a confirmed flight reservation. It is not a purchased ticket.', 20, 180)
  doc.text('This document can be presented to airline staff and immigration officials', 20, 188)
  doc.text('as proof of onward travel from Thailand.', 20, 196)

  // Branding
  doc.setFontSize(8)
  doc.text('Generated by HappyRoam Thailand \u2014 happyroam.travel', 20, 280)

  doc.save(`onward-ticket-${data.pnr}.pdf`)
}
